# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# safelist
branches:
  only:
  - develop

# Cache for R packages
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"
