// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// corC
double corC(NumericVector x, NumericVector y);
RcppExport SEXP _PRDAbeta_corC(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(corC(x, y));
    return rcpp_result_gen;
END_RCPP
}
// meanC
double meanC(NumericVector x);
RcppExport SEXP _PRDAbeta_meanC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(meanC(x));
    return rcpp_result_gen;
END_RCPP
}
// rmvrnorm_arma
arma::mat rmvrnorm_arma(int x, arma::mat Eigen_matrix);
RcppExport SEXP _PRDAbeta_rmvrnorm_arma(SEXP xSEXP, SEXP Eigen_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Eigen_matrix(Eigen_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvrnorm_arma(x, Eigen_matrix));
    return rcpp_result_gen;
END_RCPP
}
// varC
double varC(NumericVector x, double mean);
RcppExport SEXP _PRDAbeta_varC(SEXP xSEXP, SEXP meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    rcpp_result_gen = Rcpp::wrap(varC(x, mean));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PRDAbeta_corC", (DL_FUNC) &_PRDAbeta_corC, 2},
    {"_PRDAbeta_meanC", (DL_FUNC) &_PRDAbeta_meanC, 1},
    {"_PRDAbeta_rmvrnorm_arma", (DL_FUNC) &_PRDAbeta_rmvrnorm_arma, 2},
    {"_PRDAbeta_varC", (DL_FUNC) &_PRDAbeta_varC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PRDAbeta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
