# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cohen_loop <- function(sample_n1, mean_diff, sample_n2, test_method, alternative, ratio_sd = 1, mu = 0, B = 1000L) {
    .Call(`_PRDAbeta_cohen_loop`, sample_n1, mean_diff, sample_n2, test_method, alternative, ratio_sd, mu, B)
}

corC <- function(x, y) {
    .Call(`_PRDAbeta_corC`, x, y)
}

cor_loop <- function(n, alternative, B, Eigen_matrix) {
    .Call(`_PRDAbeta_cor_loop`, n, alternative, B, Eigen_matrix)
}

meanC <- function(x) {
    .Call(`_PRDAbeta_meanC`, x)
}

rmvrnorm_arma <- function(x, Eigen_matrix) {
    .Call(`_PRDAbeta_rmvrnorm_arma`, x, Eigen_matrix)
}

varC <- function(x) {
    .Call(`_PRDAbeta_varC`, x)
}

