# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corC <- function(x, y) {
    .Call(`_PRDAbeta_corC`, x, y)
}

meanC <- function(x) {
    .Call(`_PRDAbeta_meanC`, x)
}

rmvrnorm_arma <- function(x, Eigen_matrix) {
    .Call(`_PRDAbeta_rmvrnorm_arma`, x, Eigen_matrix)
}

varC <- function(x, mean) {
    .Call(`_PRDAbeta_varC`, x, mean)
}

